### PR TITLE
fixes #36 - filename#id renders as #id only

### LINKED ISSUE #36: xlink:href filename#id renders as #id only
In IE 11, when using svgxuse.js I noticed that my xlink:href value in the source code is not the same as what renders in the DOM.

    <div class="glyph fs1">
        <svg class="icon icon-palette"><use xlink:href="symbol-defs.svg#icon-palette"></use></svg>
    </div>
turns out like this:

    <div class="glyph fs1">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-paper-plane">
            <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-paper-plane" />
        </svg>
    </div>

This is a problem if you are switching svg files dynamically. Without the full path, IE keep referencing the previous file. I run into this problem because we have icon sprite sheets for multiple sizes and #id points to multiple matches as I switch around sprite sheets.

I have:

icons.svg
/24/icons.svg
/48/icons.svg

All of them have the same set of icons (same id's) but the larger icons have more detail. if I swap the url in the xlink:href using JavaScript, I end up rendering the wrong svg because svgxuse.js trims everything but the #.

### PR DESCRIPTION
**Pull request by ghost**
I just updated bower_components for the demo of it working, removing the modified code in bower_components, you should be able to see the issue of the icon not showing up.

Let me know if there is anything I can do to help further, thanks!

RE: https://github.com/Keyamoon/svgxuse/issues/36

TODO: minification / bowerifcation, i don't know the minification process or how to bower this.

### CODE REVIEW

**Comment by Keyamoon** [comment]
I'm afraid this is not the right solution. By adding the `base` before `#`, you're making a relative URL, which is not the same as referencing an id in the same html page.

**Comment by ghost** [comment]
Hmm, would like to learn more. is the value supposed to be href="#id"?

**Comment by Keyamoon** [comment]
Yes. If the value of `xlink:href` is like `filename.svg#id` and the browser fails to load it, svgxuse would fetch `filename.svg` and prepend it to `body`. It then updates the value of `xlink:href` to `#id`.

**Comment by ghost** [comment]
I think i'm following, let me dig in a bit more.

**Comment by ghost** [comment]
This PR was super off point, should probably close. If I figure something out i'll send over another.

**Pull request closed without merging**
