### PR TITLE
fix: edge case where dynamically loaded element is off canvas

### PR DESCRIPTION
**Pull request by admosity**
Issues were happening on Chrome and IE. Firefox and Safari seemed fine.

### Before and after with Chrome on a local test environment

Before:
image

After:
image

### CODE REVIEW

**Comment by Keyamoon** [comment]
Could you provide a reduced test case to replicate this issue? I need to find the root cause of the problem first.

Does your SVG have this attribute: `xmlns:xlink="http://www.w3.org/1999/xlink"`? It sounds like it could be what's causing the problem.

**Comment by admosity** [comment]
The svg was generated from icomoon:

```
<svg style="position: absolute; width: 0; height: 0; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```

I will try to create a reduced test case, but pretty busy at the moment. More details about this... 

On chrome when the svg is not cached, it will fire a request to retrieve the svg. On our production environment, this issue does not happen as the svg has been cached.

**Comment by admosity** [comment]
I am still running into this issue with no real concrete way to reproduce it... This is happening across several projects for my client. I tried spinning up a new project and haven't quite been able to reproduce it myself. There seems to be some kind of race condition on slower machines and a repaint seems to rectify the issue in most cases after the svg has been loaded and added to the dom.

Everything is on top of an angular 4 app if that helps.

**Comment by admosity** [comment]
Appears to be fixed from the latest version.

**Pull request closed without merging**
